EXT2FS_DIR := src/servers/fs/ext2
EXT2FS_COMPILE_SRCS := $(EXT2FS_DIR)/ext2fs.c $(EXT2FS_DIR)/block.c
EXT2FS_INCLUDED_SRCS := $(EXT2FS_DIR)/disk.c $(EXT2FS_DIR)/path.c $(EXT2FS_DIR)/xattr.c $(EXT2FS_DIR)/vfs.c
EXT2FS_HDRS := $(EXT2FS_DIR)/ext2.h $(EXT2FS_DIR)/block.h
