#ifndef ROBU_TESTREPORT_H
#define ROBU_TESTREPORT_H
#define TEST_REPORT_KIND_BENCH 1
#define TEST_REPORT_KIND_NOTIF_LATENCY   2
#define TEST_REPORT_KIND_GRANT_THROUGHPUT 3
#define TEST_REPORT_KIND_ABI 4
#define TEST_REPORT_KIND_ARGVTEST 6
#define TEST_REPORT_KIND_DESTROY 5
#define TEST_REPORT_KIND_EXIT 7
#define TEST_REPORT_KIND_LIBC_FDTEST 8
#define TEST_REPORT_KIND_RAMFS_TEST 9
#define TEST_REPORT_KIND_SPAWN_TEST 10
#define TEST_REPORT_KIND_SIGNAL_TEST 11
#define TEST_REPORT_KIND_CONSOLE_TEST 12
#define TEST_REPORT_KIND_MOUSE_TEST 13
#define TEST_REPORT_KIND_FB_TEST 14
#define TEST_REPORT_KIND_SHM_TEST 15
#define TEST_REPORT_KIND_SOCK_TEST 16
#endif
